test

diff --git a/build.jenkinsfile b/build.jenkinsfile
--- a/build.jenkinsfile
+++ b/build.jenkinsfile
@@ -2,92 +2,104 @@ pipeline {
     agent any
 
     environment {
-        DOCKER_IMAGE = 'etcsys/python-app:77'
-        DOCKER_REGISTRY = 'your-docker-registry'
-        SNYK_TOKEN = credentials('snyk-token')
+        PYTHON_IMG_NAME = "python-app:${BUILD_NUMBER}"
+        NGINX_IMG_NAME = "nginx-static:${BUILD_NUMBER}"
+        SNYK_TOKEN = credentials('snyk-token') // Ensure you have a Jenkins credential with ID 'snyk-token'
     }
 
     stages {
-        stage('Checkout SCM') {
+        stage('Setup Docker Buildx') {
             steps {
-                checkout scm
+                sh '''
+                    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+                    docker buildx create --name mybuilder --use
+                    docker buildx inspect --bootstrap
+                '''
             }
         }
-        
-        stage('Build Docker Image') {
-            when {
-                not {
-                    expression { docker.image(DOCKER_IMAGE).exists() }
-                }
-            }
+        stage('Build Docker Images') {
             steps {
-                script {
-                    docker.build(DOCKER_IMAGE)
+                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
+                    script {
+                        // Build and push Python app image
+                        sh '''
+                            echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
+                            docker buildx build --platform linux/amd64 -t "$PYTHON_IMG_NAME" -f Dockerfile.python .
+                            docker tag "$PYTHON_IMG_NAME" exaclly/"$PYTHON_IMG_NAME"
+                            docker push exaclly/"$PYTHON_IMG_NAME"
+                        '''
+                        // Build and push Nginx image
+                        sh '''
+                            echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
+                            docker buildx build --platform linux/amd64 -t "$NGINX_IMG_NAME" -f Dockerfile.nginx .
+                            docker tag "$NGINX_IMG_NAME" exaclly/"$NGINX_IMG_NAME"
+                            docker push exaclly/"$NGINX_IMG_NAME"
+                        '''
+                    }
                 }
             }
         }
 
         stage('Install Dependencies') {
             steps {
-                sh 'pip install -r requirements.txt'
+                sh 'pip3 install pytest unittest2 pylint'
             }
         }
 
-        stage('Linting') {
-            steps {
-                script {
-                    try {
-                        docker.image(DOCKER_IMAGE).inside('-v $WORKSPACE:/app -w /app') {
-                            sh 'flake8 .'
+        stage('Parallel Linting and Unittest') {
+            parallel {
+                stage('Static Code Linting') {
+                    steps {
+                        sh 'python3 -m pylint -f parseable --reports=no *.py > pylint.log'
+                    }
+                    post {
+                        always {
+                            sh 'cat pylint.log'
+                            recordIssues (
+                                enabledForFailure: true,
+                                aggregatingResults: true,
+                                tools: [pyLint(name: 'Pylint', pattern: '**/pylint.log')]
+                            )
                         }
-                    } catch (Exception e) {
-                        currentBuild.result = 'FAILURE'
-                        throw e
+                    }
+                }
+                stage('Unittest') {
+                    steps {
+                        script {
+                            // Run unit tests
+                            sh 'python3 -m pytest --junitxml results.xml tests/test_demo.py'
+                        }
+                    }
+                    post {
+                        always {
+                            junit allowEmptyResults: true, testResults: 'results.xml'
+                        }
                     }
                 }
             }
         }
 
-        stage('Pylint') {
+        stage('Snyk Scan Python Image') {
             steps {
-                script {
-                    try {
-                        docker.image(DOCKER_IMAGE).inside('-v $WORKSPACE:/app -w /app') {
-                            sh 'pylint app.py'
-                        }
-                    } catch (Exception e) {
-                        currentBuild.result = 'FAILURE'
-                        throw e
+                withCredentials([string(credentialsId: 'snyk-token', variable: 'SNYK_TOKEN')]) {
+                    withEnv(["SNYK_TOKEN=${SNYK_TOKEN}"]) {
+                        sh '''
+                            snyk auth $SNYK_TOKEN
+                            snyk container test exaclly/$PYTHON_IMG_NAME --file=Dockerfile.python --policy-path=.snyk
+                        '''
                     }
                 }
             }
         }
 
-        stage('Unit Tests') {
+        stage('Snyk Scan Nginx Image') {
             steps {
-                script {
-                    try {
-                        docker.image(DOCKER_IMAGE).inside('-v $WORKSPACE:/app -w /app') {
-                            sh 'pytest'
-                        }
-                    } catch (Exception e) {
-                        currentBuild.result = 'FAILURE'
-                        throw e
-                    }
-                }
-            }
-        }
-
-        stage('Snyk Security Scans') {
-            steps {
-                script {
-                    try {
-                        docker.image(DOCKER_IMAGE).inside('-v $WORKSPACE:/app -w /app') {
-                            sh 'snyk test'
-                        }
-                    } catch (Exception e) {
-                        currentBuild.result = 'FAILURE'
-                        throw e
+                withCredentials([string(credentialsId: 'snyk-token', variable: 'SNYK_TOKEN')]) {
+                    withEnv(["SNYK_TOKEN=${SNYK_TOKEN}"]) {
+                        sh '''
+                            snyk auth $SNYK_TOKEN
+                            snyk container test exaclly/$NGINX_IMG_NAME --file=Dockerfile.nginx --policy-path=.snyk
+                        '''
                     }
                 }
             }
@@ -95,7 +107,25 @@ pipeline {
 
         stage('Deploy Containers') {
             steps {
-                // Deployment steps here
+                script {
+                    def dockerComposeContent = """
+                    version: '3.8'
+
+                    services:
+                      python_app:
+                        image: exaclly/$PYTHON_IMG_NAME
+                        ports:
+                          - "8000:8000"
+
+                      nginx:
+                        image: exaclly/$NGINX_IMG_NAME
+                        ports:
+                          - "8445:8444"
+                    """
+                    writeFile file: 'docker-compose.yaml', text: dockerComposeContent
+                    sh 'docker-compose down'
+                    sh 'docker-compose up -d'
+                }
             }
         }
     }
@@ -103,19 +133,34 @@ pipeline {
     post {
         always {
             script {
+                // Log the start of the cleanup process
+                echo 'Starting cleanup process...'
+
+                // Remove the built Docker images from the disk
                 try {
-                    sh "docker rmi ${DOCKER_IMAGE}"
+                    sh '''
+                        echo "Removing Docker image: exaclly/$PYTHON_IMG_NAME"
+                        docker rmi exaclly/$PYTHON_IMG_NAME || echo "Image exaclly/$PYTHON_IMG_NAME already removed or not found."
+                    '''
                 } catch (Exception e) {
-                    echo "Image ${DOCKER_IMAGE} already removed or not found."
+                    echo "Error during Docker image removal: ${e.getMessage()}"
                 }
+
                 try {
-                    sh "docker rmi etcsys/nginx-static:77"
+                    sh '''
+                        echo "Removing Docker image: exaclly/$NGINX_IMG_NAME"
+                        docker rmi exaclly/$NGINX_IMG_NAME || echo "Image exaclly/$NGINX_IMG_NAME already removed or not found."
+                    '''
                 } catch (Exception e) {
-                    echo "Image etcsys/nginx-static:77 already removed or not found."
+                    echo "Error during Docker image removal: ${e.getMessage()}"
                 }
+
+                // Clean the workspace
+                cleanWs()
+
+                // Log the end of the cleanup process
+                echo 'Cleanup process completed.'
             }
-            cleanWs()
-            echo 'Cleanup process completed.'
         }
     }
 }
